### ISSUE TITLE
Unable to get it to work on .Net Core 3.1

### ISSUE THREAD

**Issue by bfahm** [toddmeinershagen/NLog.SignalR#11]
Kindly provide additional info on how to register and connect to the "LoggingHub". 

-  What is the name of the channel that I should listen to?
-  What is the name of the endpoint that is mapped?
- Should I map it myself or is it mapped automatically?
- What value should I pass to "uri" in the Nlog.config file? Should it be the endpoint of the hub or the Base URL of the whole application?

Thanks in advance.

**Comment by toddmeinershagen** [comment]
@bfahm - @snakefoot has updated the project to support .NET standard 2.0 which should support the use of .NET core 3.1.  It has now been release as [v4.2.0](https://github.com/toddmeinershagen/NLog.SignalR/releases/tag/v4.2.0).  

There are a couple projects in the solution that provide a sample of a console app that publishes events that the website will listen to.  ([here](https://github.com/toddmeinershagen/NLog.SignalR/tree/master/src/NLog.SignalR.Sample.Command) and [here](https://github.com/toddmeinershagen/NLog.SignalR/tree/master/src/NLog.SignalR.Sample.Web) )  

Take a look at their configurations to see if that answers your questions.  Hope it helps!
